const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE='band-repertoire-tablet-v1';let data=load(),deferredInstall=null,currentLive=[],liveIndex=0;
const DROPBOX_KEY='h5b4olc7fx5b56e',DROPBOX_ROOT='/Band-Repertoire-Sync',DROPBOX_STORE='band-repertoire-dropbox-v1';let dropbox=JSON.parse(localStorage.getItem(DROPBOX_STORE)||'{}');
function empty(){return{version:1,songs:[],setlists:[],updatedAt:new Date().toISOString()}}
function load(){try{return JSON.parse(localStorage.getItem(STORE))||empty()}catch{return empty()}}
function persist(){data.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(data));render()}
const uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random();
const seconds=v=>{let p=String(v||'').split(':').map(Number);return p.length===2?p[0]*60+p[1]:Number(v)||0};
const duration=s=>{s=Number(s)||0;return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}

async function fileDB(){return new Promise((res,rej)=>{let q=indexedDB.open('BandRepertoireFiles',1);q.onupgradeneeded=()=>q.result.createObjectStore('files',{keyPath:'id'});q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putFile(file){let db=await fileDB(),id=uid();await new Promise((res,rej)=>{let t=db.transaction('files','readwrite');t.objectStore('files').put({id,name:file.name,type:file.type||typeFor(file.name),blob:file});t.oncomplete=res;t.onerror=()=>rej(t.error)});db.close();return{id,name:file.name,type:file.type||typeFor(file.name),size:file.size}}
async function getFile(id){let db=await fileDB();let row=await new Promise((res,rej)=>{let q=db.transaction('files').objectStore('files').get(id);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});db.close();return row}
async function deleteFile(id){let db=await fileDB();await new Promise((res,rej)=>{let t=db.transaction('files','readwrite');t.objectStore('files').delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)});db.close()}
const typeFor=n=>({pdf:'application/pdf',txt:'text/plain',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png'}[n.split('.').pop().toLowerCase()]||'application/octet-stream');

const b64url=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function connectDropbox(){let raw=crypto.getRandomValues(new Uint8Array(64)),verifier=b64url(raw),challenge=b64url(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)));let url='https://www.dropbox.com/oauth2/authorize?'+new URLSearchParams({client_id:DROPBOX_KEY,response_type:'code',code_challenge:challenge,code_challenge_method:'S256',token_access_type:'offline',scope:'files.metadata.read files.content.read files.content.write'});let ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);if(ios){prompt('Kopieer de volledige link hieronder. Open daarna Safari, plak de link in de adresbalk en geef Dropbox toestemming. Ga vervolgens terug naar deze app.',url)}else{window.open(url,'_blank')}let code=prompt('Na Toestaan toont Dropbox een code. Kopieer die code en plak hem hier:');if(!code)return;setSyncStatus('Dropbox koppelen…');try{let response=await fetch('https://api.dropboxapi.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code:code.trim(),grant_type:'authorization_code',client_id:DROPBOX_KEY,code_verifier:verifier})});if(!response.ok)throw Error(await response.text());dropbox=await response.json();dropbox.expires_at=Date.now()+Number(dropbox.expires_in||14400)*1000-60000;localStorage.setItem(DROPBOX_STORE,JSON.stringify(dropbox));updateDropboxUI();await syncDropbox()}catch(e){setSyncStatus('Koppelen mislukt: '+e.message,true)}}
async function token(){if(!dropbox.refresh_token&&!dropbox.access_token)throw Error('Dropbox is nog niet gekoppeld.');if(dropbox.refresh_token&&Date.now()>Number(dropbox.expires_at||0)){let r=await fetch('https://api.dropboxapi.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:dropbox.refresh_token,client_id:DROPBOX_KEY})});if(!r.ok)throw Error(await r.text());let fresh=await r.json();dropbox={...dropbox,...fresh,expires_at:Date.now()+Number(fresh.expires_in||14400)*1000-60000};localStorage.setItem(DROPBOX_STORE,JSON.stringify(dropbox))}return dropbox.access_token}
async function dropboxDownload(path){let r=await fetch('https://content.dropboxapi.com/2/files/download',{method:'POST',headers:{Authorization:'Bearer '+await token(),'Dropbox-API-Arg':JSON.stringify({path})}});if(!r.ok)throw Error(await r.text());return r.blob()}
async function syncDropbox(){if(!dropbox.refresh_token&&!dropbox.access_token)return connectDropbox();$('#syncBtn').disabled=true;setSyncStatus('Synchronisatiebestand ophalen…');try{let manifest=JSON.parse(await (await dropboxDownload(DROPBOX_ROOT+'/manifest.json')).text());if(manifest.format!=='band-repertoire-sync')throw Error('Onbekend synchronisatieformaat.');let songs=manifest.songs.map(s=>({id:'w'+s.id,title:s.title,artist:s.artist,key:s.key,bpm:s.bpm||'',duration:s.duration||0,status:s.status||'Oefenen',notes:[s.remarks,s.notes,s.band_agreements].filter(Boolean).join('\n\n'),lyrics:s.lyrics||'',files:[]}));for(let [index,f] of manifest.files.entries()){let song=songs.find(s=>s.id==='w'+f.song_id);if(!song)continue;setSyncStatus(`Document ${index+1}/${manifest.files.length}: ${f.display_name}`);let blob=await dropboxDownload(DROPBOX_ROOT+'/files/'+f.stored_path.split('/').pop()),id='dbx-'+f.id,file=new File([blob],f.display_name,{type:blob.type||typeFor(f.display_name)});await putFileWithId(id,file);song.files.push({id,name:f.display_name,type:file.type,size:file.size})}let sets=manifest.setlists.map(sl=>{let secs=manifest.sections.filter(x=>x.setlist_id===sl.id).sort((a,b)=>a.sort_order-b.sort_order),items=[];for(let sec of secs){let sectionItems=manifest.items.filter(x=>x.section_id===sec.id).sort((a,b)=>a.sort_order-b.sort_order);for(let i of sectionItems)items.push(i.item_type==='break'?{id:'wi'+i.id,type:'break',label:i.label||'Pauze',duration:i.duration||0}:{id:'wi'+i.id,type:'song',songId:'w'+i.song_id})}return{id:'ws'+sl.id,name:sl.name,items}});data={version:1,songs,setlists:sets,updatedAt:manifest.generated_at||new Date().toISOString()};persist();setSyncStatus('✓ Bijgewerkt en offline beschikbaar: '+new Date().toLocaleString('nl-NL'));localStorage.setItem('band-repertoire-last-sync',new Date().toISOString())}catch(e){setSyncStatus('Synchronisatie mislukt: '+e.message,true)}finally{$('#syncBtn').disabled=false}}
async function putFileWithId(id,file){let db=await fileDB();await new Promise((res,rej)=>{let t=db.transaction('files','readwrite');t.objectStore('files').put({id,name:file.name,type:file.type||typeFor(file.name),blob:file});t.oncomplete=res;t.onerror=()=>rej(t.error)});db.close()}
function setSyncStatus(text,error=false){$('#syncStatus').textContent=text;$('#syncStatus').className=error?'status-warn':'status-ok'}
function updateDropboxUI(){let connected=!!(dropbox.refresh_token||dropbox.access_token);$('#dropboxConnect').textContent=connected?'Dropbox opnieuw koppelen':'Dropbox koppelen';$('#syncBtn').disabled=!connected;let last=localStorage.getItem('band-repertoire-last-sync');if(connected&&!$('#syncStatus').textContent)setSyncStatus(last?'Laatste synchronisatie: '+new Date(last).toLocaleString('nl-NL'):'Gekoppeld — nog niet gesynchroniseerd')}

function render(){renderSongs();renderSets();$('#storageInfo').textContent=`${data.songs.length} nummers · ${data.setlists.length} setlijsten · laatst opgeslagen ${new Date(data.updatedAt).toLocaleString('nl-NL')}`}
function renderSongs(){let q=$('#search').value.toLowerCase(),st=$('#statusFilter').value;let rows=data.songs.filter(s=>(!q||`${s.title} ${s.artist}`.toLowerCase().includes(q))&&(!st||s.status===st));$('#songList').innerHTML=rows.length?rows.map(s=>`<article class="card" data-id="${s.id}"><h3>${esc(s.title)}</h3><p>${esc(s.artist||'Onbekende artiest')}</p><div class="chips"><span class="chip">${esc(s.key||'—')}</span><span class="chip">${esc(s.bpm||'—')} BPM</span><span class="chip">${duration(s.duration)}</span><span class="chip">${esc(s.status)}</span></div><p>${esc(s.notes||'')}</p><div class="card-actions"><button data-edit="${s.id}">Bewerken</button><button class="accent" data-open="${s.id}">Openen</button></div></article>`).join(''):'<div class="hero"><h2>Nog geen nummers</h2><p>Voeg je eerste nummer toe of importeer een back-up.</p></div>'}
function renderSets(){let sel=$('#setSelect'),old=sel.value;sel.innerHTML=data.setlists.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(old&&data.setlists.some(x=>x.id===old))sel.value=old;let set=data.setlists.find(x=>x.id===sel.value)||data.setlists[0];if(!set){$('#setItems').innerHTML='<div class="hero">Maak eerst een setlijst.</div>';$('#setSummary').textContent='';return}sel.value=set.id;let total=set.items.reduce((n,i)=>n+(i.type==='break'?i.duration:(data.songs.find(s=>s.id===i.songId)?.duration||0)),0);$('#setSummary').textContent=`${set.items.filter(i=>i.type==='song').length} nummers · totale duur ${duration(total)}`;$('#setItems').innerHTML=set.items.map((i,n)=>{if(i.type==='break')return`<div class="set-row break" draggable="true" data-item="${i.id}"><b>—</b><span>${esc(i.label)}</span><span>${duration(i.duration)}</span><button data-remove-item="${i.id}">✕</button></div>`;let s=data.songs.find(x=>x.id===i.songId);return s?`<div class="set-row" draggable="true" data-item="${i.id}"><b>${n+1}</b><span><strong>${esc(s.title)}</strong><br><small>${esc(s.artist)}</small></span><span class="minor">${esc(s.key)} · ${esc(s.bpm||'—')} BPM</span><button data-remove-item="${i.id}">✕</button></div>`:''}).join('')}

function openEditor(id){let s=data.songs.find(x=>x.id===id)||{id:'',title:'',artist:'',key:'',bpm:'',duration:0,status:'Oefenen',notes:'',lyrics:'',files:[]},f=$('#songForm');for(let name of ['id','title','artist','key','bpm','status','notes','lyrics'])f.elements[name].value=s[name]||'';f.elements.duration.value=duration(s.duration);renderDialogFiles(s);$('#songDialog').showModal()}
function renderDialogFiles(s){$('#dialogFiles').innerHTML=(s.files||[]).map(f=>`<div class="file-line"><span>${esc(f.name)}</span><small>${Math.round(f.size/1024)} kB</small><button type="button" data-delete-file="${f.id}">Verwijder</button></div>`).join('')}
async function saveSong(e){e.preventDefault();let f=$('#songForm'),id=f.elements.id.value||uid(),old=data.songs.find(x=>x.id===id),files=old?.files||[];for(let file of $('#songFiles').files)files.push(await putFile(file));let song={id,title:f.elements.title.value.trim(),artist:f.elements.artist.value.trim(),key:f.elements.key.value.trim(),bpm:f.elements.bpm.value.trim(),duration:seconds(f.elements.duration.value),status:f.elements.status.value,notes:f.elements.notes.value,lyrics:f.elements.lyrics.value,files};if(!song.title)return;let ix=data.songs.findIndex(x=>x.id===id);ix<0?data.songs.push(song):data.songs[ix]=song;$('#songFiles').value='';$('#songDialog').close();persist()}

function showPicker(){let set=data.setlists.find(x=>x.id===$('#setSelect').value);if(!set)return;$('#pickerList').innerHTML=data.songs.map(s=>`<button class="file-line" data-pick-song="${s.id}"><span>${esc(s.title)} — ${esc(s.artist)}</span><b>+</b></button>`).join('');$('#pickerDialog').showModal()}
function addSongToSet(songId){let set=data.setlists.find(x=>x.id===$('#setSelect').value);set.items.push({id:uid(),type:'song',songId});$('#pickerDialog').close();persist()}

async function openViewer(songId,list=data.songs){currentLive=list.filter(Boolean);liveIndex=Math.max(0,currentLive.findIndex(s=>s.id===songId));await drawViewer();$('#viewer').classList.remove('hidden')}
async function drawViewer(){let s=currentLive[liveIndex];if(!s)return;$('#viewTitle').textContent=s.title;$('#viewMeta').textContent=`${s.artist||''} · ${s.key||'—'} · ${s.bpm||'—'} BPM`;$('#lyricsPane').textContent=s.lyrics||s.notes||'Geen tekst of opmerkingen.';let pane=$('#documentPane');pane.innerHTML='<p>Geen gekoppeld document.</p>';if(s.files?.length){let row=await getFile(s.files[0].id);if(row){let url=URL.createObjectURL(row.blob),pdf=row.type==='application/pdf'||row.name.toLowerCase().endsWith('.pdf');if(row.type.startsWith('image/'))pane.innerHTML=`<img src="${url}" alt="${esc(row.name)}">`;else if(row.type==='text/plain')pane.textContent=await row.blob.text();else if(pdf)await renderPdf(row.blob,pane);else pane.innerHTML=`<iframe src="${url}" title="${esc(row.name)}"></iframe>`}}$('#prevSong').disabled=liveIndex===0;$('#nextSong').disabled=liveIndex>=currentLive.length-1}
async function renderPdf(blob,pane){pane.innerHTML='<p>PDF laden…</p>';try{let pdfjs=await import('./vendor/pdfjs/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='./vendor/pdfjs/pdf.worker.mjs';let pdf=await pdfjs.getDocument({data:new Uint8Array(await blob.arrayBuffer())}).promise;pane.innerHTML='';let pages=document.createElement('div');pages.style.cssText='display:flex;flex-direction:column;gap:14px;width:100%';pane.appendChild(pages);for(let number=1;number<=pdf.numPages;number++){let page=await pdf.getPage(number),base=page.getViewport({scale:1}),scale=Math.min(2,Math.max(320,pane.clientWidth-40)/base.width),viewport=page.getViewport({scale}),pixelRatio=Math.min(window.devicePixelRatio||1,1.5),canvas=document.createElement('canvas'),context=canvas.getContext('2d');canvas.width=Math.floor(viewport.width*pixelRatio);canvas.height=Math.floor(viewport.height*pixelRatio);canvas.style.cssText='display:block;width:100%;height:auto;background:white;box-shadow:0 2px 12px #000;border-radius:4px';pages.appendChild(canvas);await page.render({canvasContext:context,transform:pixelRatio===1?null:[pixelRatio,0,0,pixelRatio,0,0],viewport}).promise}}catch(error){pane.innerHTML=`<div class="status-warn"><h3>PDF kon niet worden getoond</h3><p>${esc(error.message||error)}</p><p>Synchroniseer opnieuw en probeer het daarna nogmaals.</p></div>`}}
function startLive(){let set=data.setlists.find(x=>x.id===$('#setSelect').value);let list=set?set.items.filter(i=>i.type==='song').map(i=>data.songs.find(s=>s.id===i.songId)):data.songs;if(!list.length)return alert('Voeg eerst nummers toe.');openViewer(list[0].id,list)}

async function offlineCheck(){let missing=[];for(let s of data.songs)for(let f of s.files||[])if(!await getFile(f.id))missing.push(`${s.title}: ${f.name}`);$('#offlineReport').innerHTML=missing.length?`<div class="hero status-warn"><h3>Niet compleet</h3><p>${missing.map(esc).join('<br>')}</p></div>`:`<div class="hero status-ok"><h3>✓ Alles lokaal beschikbaar</h3><p>${data.songs.length} nummers en alle gekoppelde documenten staan op deze tablet.</p></div>`}
function exportData(){let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`band-repertoire-${new Date().toISOString().slice(0,10)}.json`;a.click()}
async function importData(file){try{let incoming=JSON.parse(await file.text());if(!Array.isArray(incoming.songs)||!Array.isArray(incoming.setlists))throw Error('Ongeldig bestand');data=incoming;persist();alert('Back-up geïmporteerd. Documentbestanden moeten apart opnieuw worden toegevoegd.')}catch(e){alert('Importeren mislukt: '+e.message)}}
function demo(){if(data.songs.length&&!confirm('Voorbeeldgegevens toevoegen naast je bestaande nummers?'))return;let a={id:uid(),title:'Lily Was Here',artist:'Candy Dulfer',key:'Dm',bpm:'92',duration:270,status:'Speelklaar',notes:'Tenorsax — intro niet spelen — solo 2:35',lyrics:'',files:[]},b={id:uid(),title:'Valerie',artist:'Amy Winehouse',key:'Eb',bpm:'106',duration:235,status:'Bijna klaar',notes:'Tweede stem in refrein',lyrics:'Couplet 1\n\nRefrein',files:[]};data.songs.push(a,b);data.setlists.push({id:uid(),name:'Optreden',items:[{id:uid(),type:'song',songId:a.id},{id:uid(),type:'song',songId:b.id},{id:uid(),type:'break',label:'Pauze',duration:900}]});persist()}

$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(p=>p.classList.toggle('active',p.id===b.dataset.page))});
$('#search').oninput=renderSongs;$('#statusFilter').onchange=renderSongs;$('#newSong').onclick=()=>openEditor();$('#songForm').onsubmit=saveSong;$('#songList').onclick=e=>{let id=e.target.dataset.edit||e.target.dataset.open;if(e.target.dataset.edit)openEditor(id);if(e.target.dataset.open)openViewer(id)};
$('#dialogFiles').onclick=async e=>{let id=e.target.dataset.deleteFile;if(!id)return;let song=data.songs.find(x=>x.id===$('#songForm').elements.id.value);if(song){await deleteFile(id);song.files=song.files.filter(f=>f.id!==id);renderDialogFiles(song);persist()}};
$('#newSet').onclick=()=>{let name=prompt('Naam van de setlijst:','Optreden');if(name){data.setlists.push({id:uid(),name,items:[]});persist()}};$('#setSelect').onchange=renderSets;$('#addToSet').onclick=showPicker;$('#pickerList').onclick=e=>{let b=e.target.closest('[data-pick-song]');if(b)addSongToSet(b.dataset.pickSong)};$('#addBreak').onclick=()=>{let set=data.setlists.find(x=>x.id===$('#setSelect').value),label=prompt('Naam:','Pauze'),d=prompt('Duur:','15:00');if(set&&label){set.items.push({id:uid(),type:'break',label,duration:seconds(d)});$('#pickerDialog').close();persist()}};$('#setItems').onclick=e=>{let id=e.target.dataset.removeItem,set=data.setlists.find(x=>x.id===$('#setSelect').value);if(id&&set){set.items=set.items.filter(i=>i.id!==id);persist()}};
let dragged=null;$('#setItems').ondragstart=e=>dragged=e.target.closest('[data-item]')?.dataset.item;$('#setItems').ondragover=e=>e.preventDefault();$('#setItems').ondrop=e=>{e.preventDefault();let target=e.target.closest('[data-item]')?.dataset.item,set=data.setlists.find(x=>x.id===$('#setSelect').value);if(dragged&&target&&set&&dragged!==target){let from=set.items.findIndex(i=>i.id===dragged),to=set.items.findIndex(i=>i.id===target);set.items.splice(to,0,set.items.splice(from,1)[0]);persist()}};
$('#liveBtn').onclick=startLive;$('#closeViewer').onclick=()=>$('#viewer').classList.add('hidden');$('#nextSong').onclick=async()=>{if(liveIndex<currentLive.length-1){liveIndex++;await drawViewer()}};$('#prevSong').onclick=async()=>{if(liveIndex>0){liveIndex--;await drawViewer()}};$('#offlineCheck').onclick=offlineCheck;$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#demoBtn').onclick=demo;
$('#dropboxConnect').onclick=connectDropbox;$('#syncBtn').onclick=syncDropbox;updateDropboxUI();
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
